Multi species + Refactoring
ergodicio/inverse-thomson-scattering pull request #35
Opened 2023-11-15 02:28 UTC by joglekara

2023-11-16 16:24 UTC, almilder commented on configs/1d/defaults.yaml
the changes to line 132, 153, and 155 should not be propagated to main. lines 180 and 186 are good

2023-11-16 16:25 UTC, joglekara commented on configs/1d/defaults.yaml
i think we at least need a placeholder there because it looks for those quantities, no?

2023-11-16 16:26 UTC, almilder commented on configs/1d/inputs.yaml
Only lines 39, 44-47 should be propagated to main so that the input deck works for the test case of shot 101675

2023-11-16 16:26 UTC, almilder commented on data/EPW_CCD-s104035.hdf
Remove

2023-11-16 16:27 UTC, almilder commented on data/IAW_CCD-s104035.hdf
Remove

2023-11-16 16:38 UTC, almilder commented on inverse_thomson_scattering/model/physics/generate_spectra.py
what does the input "backend" do? it does not appear to be used at all

2023-11-16 16:52 UTC, almilder commented on inverse_thomson_scattering/process/lineouts.py
line 19 should be:
LineoutPixelI = np.round(np.array(LineoutPixelI) - IAWtime).astype(int)

2023-11-16 16:57 UTC, almilder commented on inverse_thomson_scattering/process/postprocess.py
Do we need the best_weights, raw_weights, and all_params?

2023-11-16 16:58 UTC, almilder commented on inverse_thomson_scattering/process/postprocess.py
Have you tried getting sigmas with the multi-species running?

2023-11-16 16:59 UTC, almilder commented on run.py
I would comment out line 8

2023-11-16 17:00 UTC, almilder commented on run.py
And switch the deck that's referenced to configs/1d

2023-11-16 17:02 UTC, almilder commented on inverse_thomson_scattering/singlepass.py
looks like most of these imports are not used

2023-11-16 17:03 UTC, almilder requested changes
Looks good, just a few minor things in the comments

2023-11-16 17:06 UTC, almilder commented on configs/1d/defaults.yaml
It need to have quantities in those fields but we should keep the old values not use the new ones

2023-11-26 16:50 UTC, joglekara commented on inverse_thomson_scattering/model/physics/generate_spectra.py
it used to be for haiku vs pure jax. Removed it

2023-11-26 18:04 UTC, joglekara commented on inverse_thomson_scattering/process/postprocess.py
let me take that in a separate pr

2023-11-26 18:04 UTC, joglekara commented on inverse_thomson_scattering/process/postprocess.py
let me take that in a separate pr

2023-11-26 18:15 UTC, joglekara commented on run.py
we have a new runner that uses command line args with no defaults yet, we can discuss what those are. lets leave that for the next PR

2023-11-26 18:17 UTC, joglekara commented
Okay all done. There's a few things we should address in future PRs

those are
- command line defaults 
- add to readthedocs 
- sigmas for multi species
- refactor best_weights, raw_weights

this is 1k lines already and it is passing tests

2023-12-01 16:36 UTC, merged