Re-enable ADAM for 1D (non-angular) analysis
ergodicio/inverse-thomson-scattering pull request #42
Opened 2024-01-05 16:58 UTC by joglekara

See https://continuum.ergodic.io/experiments/#/experiments/298/runs/4f51caccbed94c699ea9eeb1437771ba vs https://continuum.ergodic.io/experiments/#/experiments/298/runs/231ca63bf4714e71a56921615d11c6fb

2024-01-05 17:05 UTC, joglekara commented
The main difference between ADAM (from JAXopt) and L-BFGS-B (from SciPy) is that the latter has an auto-convergence stop and often terminates fairly early (for better or worse). The former requires us to implement that.

Right now, it just runs to the maximum number of steps specified in the config and returns the parameters from the step with the best loss. It will be useful to implement an early stopping condition

It will then be useful to unify the codepath for 1D lineouts and branch where needed (optimizer in this case).

Then it will be useful to extend this to angular

2024-01-05 17:26 UTC, joglekara commented
Also did some refactoring with the file storage

2024-01-08 18:38 UTC, almilder commented on configs/1d/defaults.yaml
I am not seeing the sequential field in the test runs, does this work with adam?

2024-01-08 18:43 UTC, almilder commented on configs/1d/defaults.yaml
NM i see how this works in the fitter function

2024-01-08 18:48 UTC, almilder commented on run_tsadar.py
please re-enable jit

2024-01-08 18:49 UTC, almilder requested changes
Generally looks good, but i think we need jit enabled

2024-01-09 18:04 UTC, almilder approved these changes

2024-01-09 18:10 UTC, merged